name: Fetch Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Install dependencies
        run: make install-deps

      - name: Run
        run: make run

      - name: Check for changes in Formula/aws-sso-login.rb
        id: check
        run: |
          if git diff --quiet HEAD -- Formula/aws-sso-login.rb; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
        continue-on-error: false

      - name: Commit and push changes
        if: env.no_changes == 'false'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/aws-sso-login.rb
          git commit -m "Update Formula/aws-sso-login.rb via CI/CD pipeline"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
